; This file was auto-generated by drush make
core = 7.x
api = 2

; Core
projects[drupal][version] = "7.56"

; Themes
projects[basic][version] = "4.3"

;Common modules.
projects[admin_menu][subdir] = "contrib"
projects[ctools][subdir] = "contrib"
projects[token][subdir] = "contrib"
projects[views][subdir] = "contrib"
projects[features][subdir] = "contrib"
projects[admin_menu][subdir] = "contrib"

 
; Development modules.
projects[devel][subdir] = "development"